version: "3"

services:
    app:
        environment:
            - APACHE_RUN_USER=#1000
        build:
            context: ./docker
        depends_on:
            -   laravel
        ports:
            - 1000:80
        volumes:
            - ./:/var/www/html
    laravel:
        image: postgres
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: dekanat
        ports:
            - 5433:5432
        container_name: bd
